CREATE TABLE T01_SOLICITUD (
    ID            NUMBER PRIMARY KEY,
    ESTADO        NUMBER NOT NULL, 
    FECHA_INGRESO DATE NOT NULL,
    MONTO         NUMBER(15,2) NOT NULL,
    ID_CLIENTE    VARCHAR2(50) NOT NULL
);
